- name: Making buckets
  hosts: localhost
  connection: local #boto3 is installed locally hece we are using local instead of http
  gather_facts: no
  
  vars:
      hereorthere: "present"

  vars_files:
          - ~/cred.zon
  tasks:
          - name: wheee 
            s3_bucket:
              name: chterastan123    # naming rules https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
              state: "{{ hereorthere }}"
              aws_access_key: "{{ ec2_access_key }}"
              aws_secret_key: "{{ ec2_secret_key }}"
