---
- name: Playbook - Install figlet    # metadata
  hosts: bender   # we want to take the planetexpress group and remove farnsworth
  connection: ssh     # default is to use the connection plugin ssh.py
  gather_facts: yes   # default is yes
  become: yes

  tasks:                             # a list of what we want to do
  - name: using apt to install figlet  # metadata
    apt:                     # the module we want to run, apt.py
        name: figlet         # parameter name has the value figlet
        state: present      # parameter state has the value present
  - name: using apt to install sl  # metadata
    apt:
        name: sl
        state: present
