---
- name: latest Apache version installed
  package:
    name: "{{ pkgs }}"
    state: latest
  notify:
    - restart_webservices

- name: Apache enabled and running
  service:
    name: apache2
    enabled: yes
    state: started

# Copy index.html into the service
- name: copy index.html
  copy:
    src: ~/ans/files/index.html
    dest: /var/www/html/

# if dest is directory download every time
# but only replace if destination is different
# https://raw.githubusercontent.com/rzfeeser/
#              alta3files/master/apache2.conf
- name: Download a copy of apache2.conf
  get_url:
    url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
    dest: /etc/apache2/
  notify:
      - restart_apache   # ONLY restart apache if this conf
                         # file needs updated

# ensure the MySQL service is up and running
- name: MySQL (MariaDB) is running
  service:
    name: mysql
    enabled: yes
    state: started

# if this line needs added to my.cnf
# then ONLY the MySQL service needs restarted
- name: Modify SQL conf file to listen on all interfaces
  lineinfile:
    dest: /etc/mysql/my.cnf
    regexp: "^bind-address"
    line: "bind-address=0.0.0.0"
  notify:
    - restart_mysql

