---
- name: Playbook that runs a Python script
  hosts: planetexpress
  connection: ssh
  become: yes

  tasks:
  - name: Copy script to target hosts and execute it
    script: ~/mycode/scripts/testingscript.py
    args:
      executable: /usr/bin/python3
    register: results    # save the JSON sent back by our script

  - name: Print out the 'results'
    debug:
      var: results
      # notice there is a stdout and stdout_lines

